# Generated by Django 4.2.3 on 2023-07-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booktype',
            field=models.CharField(default='booktype', max_length=100),
        ),
    ]
