# Generated by Django 4.2.3 on 2023-07-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_book_booktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
