# Generated by Django 4.2.3 on 2023-07-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
